### ISSUE TITLE
Enhance the UI of the homepage

### ISSUE THREAD

**Issue by AtriSukul1508** [AtriSukul1508/Njack_Hack_It_Out-Tur1ng-#7] opened 2023-02-13 17:27 UTC

**Comment by Suniti-0020** [comment] 2023-02-14 18:30
Hi @AtriSukul1508 I am interested in the issue , can you assign it to me . under JWOC

**Comment by SasiVardhan247** [comment] 2023-02-14 18:31
I want to work on this issue under JWOC,assign this to me

**Comment by AtriSukul1508** [comment] 2023-02-14 18:45
go ahead @Suniti-0020 , while creating a pull request, make sure to attach a screenshot

**Comment by ManasaKaza** [comment] 2023-02-14 20:01
I want to work on this issue under JWOC

**Comment by AtriSukul1508** [comment] 2023-02-17 04:23
@Suniti-0020 any updates?

**Comment by Suniti-0020** [comment] 2023-02-17 04:29
@AtriSukul1508 I will need 1 more day

**Comment by Suniti-0020** [comment] 2023-02-18 06:05
@AtriSukul1508  I have lost my complete data from my pc I will not be able to cope up with it more , you can assign to others . Sorry , for the inconveniences caused by me.....

**Comment by AtriSukul1508** [comment] 2023-02-18 06:21
@SasiVardhan247 you can now work on that

**Comment by AtriSukul1508** [comment] 2023-02-22 10:01
@SasiVardhan247 any updates ?

**Comment by SasiVardhan247** [comment] 2023-02-23 09:17
I'm unable make it .can you assign to someone

**Comment by neokd** [comment] 2023-02-23 15:43
I would like to work on this issue under JWOC

**Comment by Hritik1503** [comment] 2023-02-25 03:32
I want to work for on this issue under jwoc , please assign me

**Comment by AtriSukul1508** [comment] 2023-02-25 10:28
@neokd you can now work on that

**Comment by neokd** [comment] 2023-02-25 11:14
Thanks

**Comment by Priyamakeshwari** [comment] 2023-02-25 14:17
I would like to work on this issue under JWOC

**Closed** 2023-02-28 18:07 UTC
Labels: Hard, JWOC
